[workspace]
resolver = "3"
package.version = "0.1.0"
package.edition = "2024"
members = ["day1", "day10", "day11", "day12", "day13", "day14", "day15", "day16", "day17", "day18", "day19", "day2", "day20", "day21", "day3", "day4", "day5", "day6", "day7", "day8", "day9"]

[workspace.dependencies]
regex = "1"
itertools = "0.14"
serde_json = "1"

[workspace.lints.rust]
warnings = "deny"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
# from clippy::restriction
unwrap_used = "deny"
expect_used = "deny"
precedence_bits = "deny"
return_and_then = "deny"
map_with_unused_argument_over_ranges = "deny"
string_lit_chars_any = "deny"
redundant_type_annotations = "deny"
if_then_some_else_none = "deny"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true
